#!/usr/bin/zsh
# Declaring "universal" variables at the beginning
bglocation="$HOME/Pictures/Backgrounds/"
cd "$bglocation"
backgrounds="$(identify "$bglocation*" | awk '{print $1,$3}' | sed 's|^/.*/||')"
tall="$(bc <<< "scale=5; 1080 / 1920")"
wide="$(bc <<< "scale=5; 1920 / 1080")"
squarish="$(bc <<< "scale=5; 1280 / 1024")"

# Name says it - takes a background, assigns it to an array of the matching type.
# The three arrays are "tallarr", "widearr", and "squarearr", matching the tall, wide, and squarish resolution ratios, respectively.
for file in $bglocation*; do
	fileinfo=$(identify $file | awk '{print$1,$3}' | sed 's|^/.*/||')
	num1=$(print $fileinfo | awk '{print $2}' | grep --only-matching "^[0-9]*") #| tr -d "\n")
	num2=$(print $fileinfo | awk '{print $2}' | grep --only-matching "[0-9]*$") #| tr -d "\n")
	ratio=$(bc <<< "scale=5; $num1/$num2")
	if [[ $ratio = $tall ]] then
		tallarr+=($(print $fileinfo | awk '{print $1}'))
	elif [[ $ratio = $wide ]] then
	  widearr+=($(print $fileinfo | awk '{print $1}'))
	elif [[ $ratio = $squarish ]] then
		squarearr+=($(print $fileinfo | awk '{print $1}'))
	fi
done

tallrand=$[RANDOM % ${#tallarr[@]} + 1]
widerand=$[RANDOM % ${#widearr[@]} + 1]
squarerand=$[RANDOM % ${#squarearr[@]} + 1]

feh --bg-center "$widearr[$widerand]" "$squarearr[$squarerand]" "$tallarr[$tallrand]"
